---

AWSTemplateFormatVersion: "2010-09-09"
Description: Template Provision S3 Bucket with internet access

# Metadata:
#   template metadata

Parameters:
  DataStoreParameter:
    Type: String

  DataPolicyParameter:
    Type: String


# Rules:
#   set of rules

# Mappings:
#   set of mappings

# Conditions:
#   set of conditions

# Transform:
#   set of transforms

Resources:
  user-data-store:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Ref user-data-store
      CorsConfiguration: 
        CorsRule:
            AllowedHeaders: 
              - "*"
            AllowedMethods: 
              - Put
              - Post
              - Get
              - Delete
            AllowedOrigins: 
              - "*"
            ExposedHeaders: 
              - Date
      PublicAccessBlockConfiguration: 
          BlockPublicAcls: False
          BlockPublicPolicy: False
          IgnorePublicAcls: False
          RestrictPublicBuckets: False
      Tags: 
        - Key: "S3"
          Value: "UserData"
      VersioningConfiguration: 
        Status: Enabled
  
  Policy-data-store:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref user-data-store
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:DeleteObject
              - s3:GetObject
            Resource: '*'
        Resources:
          arn:aws:s3:::user-data-store/*


Outputs:
  DataStoreOutput:
    Description: Output for data store s3 bucket with internet access
    Value: !Ref DataStoreParameter
    Export:
      Name: !Ref user-data-store

  DataPolicyOutput:
    Description: Data Policy 
    Value: !Ref DataPolicyParameter
    Export:
      Name: !Ref Policy-data-store