AWSTemplateFormatVersion: "2010-09-09"
Description: Template for creating an S3 Bucket with internet access

# Metadata:
#   template metadata

Parameters:
  DataStoreParameter:
    Default: UserDataStore
    Description: User data object in s3 bucket
    Type: String

  DataPolicyParameter:
    Default: DataStorePolicy
    Description: bucket policy 
    Type: String

  VersioningEnabled:
    Default: 'true'
    Description: Enable versioning for the S3 bucket
    Type: String
  
# Rules:
#   set of rules

# Mappings:
#   set of mappings

# Conditions:
#   set of conditions

# Transform:
#   set of transforms


Resources:
  UserDataStore:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: all-users-info
      CorsConfiguration:
        CorsRules: 
          - AllowedHeaders: 
              - "*"
            AllowedMethods: 
              - PUT
              - GET
              - DELETE
              - POST
            AllowedOrigins: 
              - "*"
            ExposedHeaders: 
              - Date
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: False
        BlockPublicPolicy: False
        IgnorePublicAcls: False
        RestrictPublicBuckets: False
      Tags: 
        - Key: "S3"
          Value: "UserData"
      VersioningConfiguration: 
        Status: Enabled
  

  DataStorePolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref UserDataStore
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - s3:PutObject
              - s3:DeleteObject
              - s3:GetObject
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref UserDataStore
                - /*
            


Outputs:
  DataStoreOutput:
    Description: Output for data store s3 bucket with internet access
    Value: !Ref UserDataStore
    Export:
      Name: S3DataBucket

  DataPolicyOutput:
    Description: Data Policy 
    Value: !Ref DataStorePolicy
    Export:
      Name: DataBucketPolicy